### PR TITLE
Memory management

### LINKED ISSUE #42: New Memory allocation doesn't work with stack allocation
The refcount being in the Mat header doesn't work because the header can be torn down by the program stack unwinding. 
For now, let's see if things work by always dynamically allocating and destructing the base object. If that works, we can strip it down to a simpler base.

### PR DESCRIPTION
**Pull request by linalikespuzzles**

### CODE REVIEW

File: include/Mat.h [hunk 1]
```diff
@@ -5,6 +5,7 @@
 #include <initializer_list>
 #include <matMath.h>
 #include <type_traits>
+#include <cassert>//temporary while allocate is undefined
```
Comment (anuranbaka) [inline include/Mat.h:8]: rm?

File: include/Mat.h [hunk 2]
```diff
@@ -228,19 +228,55 @@ class Mat {
...
         data = new Type[list.size()];
+        base = newMat(data);
         size_type i = 0;
         for(auto elem : list){
             data[i] = elem;
             i++;
         }
+    }
+
+    Mat(std::initializer_list<Type> list, AllocInfo<Type> alloc){
```
Comment (anuranbaka) [inline include/Mat.h:266]: Add a test that uses this

File: include/Mat.h [hunk 3]
```diff
@@ -254,35 +290,62 @@ class Mat {
...
+        DimInfo dInfo(ndim, temp_dims, temp_strides);
+        allocator->allocate(this, alloc.userdata, dInfo);
+
+        size_type i = 0;
+        for(auto elem : list){
+            data[i] = elem;
+            i++;
+        }
+
         base = newMat(data);
```
Comment (anuranbaka) [inline include/Mat.h:324]: move up to match

File: include/Mat.h [hunk 4]
```diff
@@ -254,35 +290,62 @@ class Mat {
...
 
         ndim = b.ndim;
         data = b.data;
         
         if(b.allocator != NULL){
-            DimInfo dInfo(ndim, dims, strides);
-            b.allocator->allocate(this, dInfo);
+            allocator = b.allocator;
+            DimInfo dInfo(ndim, b.dims, b.strides);
+            allocator->allocate(this, allocator->userdata, dInfo);
```
Comment (anuranbaka) [inline include/Mat.h:338]: Make sure to document that allocate is responsible for detecting the difference between an initial allocation and the copy constructor. Put this doc where DimInfo is defined

File: include/Mat.h [hunk 5]
```diff
@@ -391,11 +483,12 @@ class Mat {
         ndim = b.ndim;
         data = b.data;
         
-        if(allocator != NULL){
+        assert(allocator==NULL);
+        /*if(allocator != NULL){ // check this again when removing assert after allocate is defined
             DimInfo dInfo(ndim, dims, strides);
             allocator->allocate(this, dInfo);
         }
```
Comment (anuranbaka) [inline include/Mat.h:490]: - Base matrix handles allocator for data block
- The non-base handle allocating their dims and strides using their own allocator, which they keep when they are pointed to a new base and need to reallocate their dims and strides.
- We should check that the destructors correctly use each deallocate with the matching allocators

File: include/Mat.h [hunk 6]
```diff
@@ -421,7 +514,7 @@ class Mat {
         
         if(allocator != NULL){
             DimInfo dInfo(ndim, dims, strides);
-            allocator->allocate(this, dInfo);
+            allocator->allocate(this, allocator->userdata, dInfo);
```
Comment (anuranbaka) [inline include/Mat.h:517]: Probably won't inherit the source's userdata. Will look just like a constructor

File: include/pythonAPI.h [hunk 7]
```diff
@@ -28,18 +28,26 @@ int getTypenum(){
...
+void wrap_numpy_allocate(Mat<T>* new_mat, void* userdata, const DimInfo& dim_info){ //do we need a struct or is ndim enough?
+    new_mat->dims = new size_t[dim_info.ndim];
+    new_mat->strides = new size_t[dim_info.ndim];
+    new_mat->allocator->userdata = userdata;
+    Py_INCREF((PyObject*)userdata);
+}
+
+template <class T>
+void wrap_numpy_deallocate(Mat<T>* mat){
+    Py_DECREF((PyObject*)mat->allocator->userdata);
```
Comment (anuranbaka) [inline include/pythonAPI.h:41]: For non-default allocator case(like here), move the delete lines for dims/strides to the deallocate function

File: include/Mat.h [hunk 8]
```diff
@@ -77,8 +79,38 @@ template<class Type>
...
+    }
+
+    MatBase(size_t size, AllocInfo<Type>* allocIn) : allocator(allocIn) {
+        allocator.allocateData(this, allocator.userdata, size);
+    }
+
+    MatBase(void* newdata) : data((Type*)newdata) {}
+    
+    ~MatBase(){
+        if(allocator != NULL){
```
Comment (anuranbaka) [inline include/Mat.h:107]: swap the conditions here

File: include/Mat.h [hunk 9]
```diff
@@ -77,8 +79,38 @@ template<class Type>
...
+            data = new Type[size];
+    }
+
+    MatBase(size_t size, AllocInfo<Type>* allocIn) : allocator(allocIn) {
+        allocator.allocateData(this, allocator.userdata, size);
+    }
+
+    MatBase(void* newdata) : data((Type*)newdata) {}
+    
+    ~MatBase(){
```
Comment (anuranbaka) [inline include/Mat.h:106]: For debug can check that refcounter is exactly == 0

File: include/Mat.h [hunk 10]
```diff
@@ -313,29 +352,25 @@ class Mat {
...
 
-        base = newMat(data);
     }
 
     Mat(const Mat& b){
-        if(b.base != NULL) base = b.base; //remove this later when new base type is added
-        else base = const_cast<Mat<Type>*>(&b);
-        (base->refCount)++;
-
+        base = b.base;
```
Comment (anuranbaka) [inline include/Mat.h:366]: refcount++

File: include/Mat.h [hunk 11]
```diff
@@ -403,53 +448,28 @@ class Mat {
...
-            if(refCount < 0) fprintf(stderr, "Reference counter is negative somehow\n");
-            if(refCount < 1){
-                delete []data;
-            }
+            (base->refCount)--;
             delete []dims;
             delete []strides;
             strides = NULL;
+            if(base->refCount <= 0){
+                base->~MatBase();
```
Comment (anuranbaka) [inline include/Mat.h:468]: call delete instead

File: include/Mat.h (hunk 5 above)
Comment (anuranbaka) [reply include/Mat.h:508]: deprecated:

- base handles allocating data
- headers handle allocating meta and construct a base if needed

File: include/Mat.h [hunk 12]
```diff
@@ -740,6 +770,8 @@ class Mat {
         return false;
     }
```
Comment (anuranbaka) [inline include/Mat.h:776]: continue from here

File: include/Mat.h [hunk 13]
```diff
@@ -1108,9 +1143,11 @@ class Mat {
...
 
-        result.data = data;
-        result.base = result.newMat(result.data);
-        result.base->data = NULL;
+        MatBase<Type>* newBase;
+        newBase = new MatBase<Type>(data);
+        result.base = newBase;
+        result.base->refCount++;
+        result.data = newBase->data;
         return result;
```
Comment (anuranbaka) [inline include/Mat.h:1155]: fiddle with the deallocator system to make it not delete the data here when the base is destroyed

File: include/Mat.h [hunk 14]
```diff
@@ -1126,21 +1163,24 @@ class Mat {
 
         if(alloc != NULL){
             DimInfo dInfo(new_ndim, new_dims, new_strides);
-            result.allocator->allocate(&result, result.allocator->userdata, dInfo);
+            result.allocator->allocateMeta(&result, result.allocator->userdata, dInfo);
         }
         else{
```
Comment (anuranbaka) [inline include/Mat.h:1172]: change so that first line of func is "if the allocator is NULL, call the default wrap and return" and remove the need for the else and if  down here

File: include/Mat.h [hunk 15]
```diff
@@ -341,41 +373,55 @@ class Mat {
...
+            throw invalid_argument("Initializer list size inconsistent with dimensions");
+        strides = new size_type[ndim];
 
-        temp_strides[ndim-1] = 1;
-        for(long j = ndim-2; j >= 0; j--){
-            temp_strides[j] = temp_strides[j+1]*temp_dims[j+1];
+        MatBase<Type>* newBase;
+        newBase = new MatBase<Type>();
+        base = newBase;
         }
```
Comment (anuranbaka) [inline include/Mat.h:387]: indent

File: include/Mat.h [hunk 16]
```diff
@@ -341,41 +373,55 @@ class Mat {
...
+            allocator->allocateData(base, allocator->userdata, size());
+        data = base->data;
 
         size_type i = 0;
         for(auto elem : list){
             data[i] = elem;
             i++;
         }
-
     }
```
Comment (anuranbaka) [inline include/Mat.h:408]: start here next time

File: include/Mat.h [hunk 17]
```diff
@@ -253,43 +250,59 @@ class Mat {
...
+            newBase = new MatBase<Type>();
+            base = newBase;
         }
+        else allocator->allocateMeta(this, alloc.userdata, ndim);
+        base->refCount++;
 
-        allocator = alloc;
-        DimInfo dInfo(ndim, temp_dims, temp_strides);
-        allocator->allocateMeta(this, alloc.userdata, dInfo);
+        dims = {(static_cast<size_type>(ind))...};
```
Comment (anuranbaka) [inline include/Mat.h:282]: revisit the weirdness with parameter packs here

File: include/Mat.h [hunk 18]
```diff
@@ -8,6 +8,9 @@
 
 using namespace std;
 
+#define ERROR_IF_FAILED_ALLOC false
```
Comment (anuranbaka) [inline include/Mat.h:11]: use an #ifdef instead of the actual defined value

File: include/Mat.h [hunk 19]
```diff
@@ -1189,7 +1205,7 @@ class Mat {
         result.data = data;
 
         thread_local AllocInfo<Type> wrap_alloc;
-        wrap_alloc.deallocateData = [](MatBase<Type>*){return;};
+        wrap_alloc.deallocateData = [](MatBase<Type>&){return;};
```
Comment (anuranbaka) [inline include/Mat.h:1208]: make sure it's okay to store a pointer to a local lambda

File: include/Mat.h [hunk 20]
```diff
@@ -1273,16 +1284,37 @@ class Mat {
...
-        for(long i = 0; i < a.ndim; i++){
+        if(result.allocator == NULL || result.allocator->deallocateMeta == NULL){
+            delete[] result.dims;
+            delete[] result.strides;
+        }
+        else result.allocator->deallocateMeta(result);
+
+        if(result.allocator == NULL || result.allocator->allocateMeta == NULL){
+            result.dims = new size_type[result.ndim];
+            result.strides = new size_type[result.ndim];
```
Comment (anuranbaka) [inline include/Mat.h:1307]: error out if not custom allocate+deallocate

File: include/pythonAPI.h [hunk 21]
```diff
@@ -29,30 +29,33 @@ int getTypenum(){
 }
 
 template <class T>
-void wrap_numpy_allocateMeta(Mat<T>* new_mat, void*, const long new_ndim){
-    new_mat->dims = new size_t[new_ndim];
-    new_mat->strides = new size_t[new_ndim];
-    MatBase<T>* newBase;
-    newBase = new MatBase<T>;
-    new_mat->base = newBase;
+void wrap_numpy_allocateMeta(Mat<T> &new_mat, void*, const long new_ndim){
```
Comment (anuranbaka) [inline include/pythonAPI.h:32]: If it's easy try to use pymalloc / pyfree instead of new/delete here

File: include/pythonAPI.h [hunk 22]
```diff
@@ -102,7 +105,7 @@ Mat<T> wrap_numpy(PyArrayObject* arr){
     npInfo.userdata = arrBase;
     npInfo.allocateMeta = *wrap_numpy_allocateMeta<T>;
     npInfo.deallocateMeta = *wrap_numpy_deallocateMeta<T>;
-    npInfo.allocateData = *wrap_numpy_allocateData<T>;
+    //npInfo.allocateData = *wrap_numpy_allocateData<T>;
```
Comment (anuranbaka) [inline include/pythonAPI.h:108]: bug!

Comment (anuranbaka) [reply include/pythonAPI.h:108]: test case?

File: matTest/allocTest.cpp [hunk 23]
```diff
@@ -0,0 +1,76 @@
+#include <Mat.h>
```
Comment (anuranbaka) [inline matTest/allocTest.cpp:1]: Add comment saying what this file is for/showing.

File: matTest/allocTest.cpp [hunk 24]
```diff
@@ -0,0 +1,76 @@
...
+    alloc_size_t.deallocateData = customDeallocator_Data<size_t>;
+    
+    Mat<double> a({0,1,2,3,4,5,6,7,8,9,10,11}, &alloc_double, 3, 4);
+    Mat<double> b(&alloc_double, 3, 3);
+    Mat<double> c({2,3,4}, &alloc_double);
+    Mat<double> d(a);
+    Mat<double> e = a.copy();
+    Mat<double> f = a.reshape(6,2); // one alloc while this line exists... :/
+    Mat<double> g = a.i(Mat<size_t>::arange(2,4,1,&alloc_size_t));
+
```
Comment (anuranbaka) [inline matTest/allocTest.cpp:74]: do some math or something and print outputs?

File: matTest/matTest.cpp [hunk 25]
```diff
@@ -436,7 +436,7 @@ int main (){
     output = y.i(Mat<size_t>::arange(0,3,2));
     fprintf(outFile, "assigning rows 0 and 2 of y to a matrix\n");
     output.print(outFile);
-
+    fflush(outFile);
```
Comment (anuranbaka) [inline matTest/matTest.cpp:439]: bug!
